version: '3.7'
services:
   ipfs:
      image: ipfs/go-ipfs:master-latest
      command: daemon
      ports:
         - '127.0.0.1:8080:8080'
         - '127.0.0.1:5001:5001'

   node-asylum:
      image: registry.gitlab.com/asylum-space/asylum-item-nft:latest
      command: node-asylum --dev --tmp --ws-external
      ports:
         - 9944:9944

   asylum-ui:
      build:
         context: .
      command: sh -c "yarn seed &&
         yarn start"
      depends_on:
         - ipfs
         - node-asylum
      ports:
         - 3000:3000
